project:
  type: site
  output-dir: docs
lang: pt
site:
  title: "Relatórios reprodutíveis com R"
  footer: "Página criada usando [quarto](https://quarto.org/). <br>Licença de uso: [Creative Commons Atribuição-Compartilha Igual (CC BY-SA)](licenca.qmd)."
  repo-url: https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios
  twitter-card: true
  creator: "@beamilz"
  site: "@beamilz"
  site-url: "https://www.ime.usp.br/verao/assets/images/logo_verao.png"
  image: "img/preview.png"
  navbar:
    sidebar-menus: true
    type: dark
    background: primary
    left:
    logo: https://www.ime.usp.br/verao/assets/images/logo_verao.png
    right:
      - sidebar:infos
      - sidebar:material
      - mensagens.qmd
      - icon: github
        href: https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios
  sidebar:
    - id: infos
      title: "Sobre o curso"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - section: "Informações sobre o curso"
          contents:
           - informacoes-gerais.qmd
           - profs.qmd
           - bibliografia.qmd
           - faq.qmd
    - id: material
      title: "Material"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - programacao-do-curso.qmd
        - section: "Aulas"
          contents:
           - aula1.qmd
           - aula2.qmd
           - aula3.qmd
           - aula4.qmd
           - aula5.qmd
        - section: "Trabalho final"
          contents:
           - trabalho_final.qmd
        - section: "Sobre o material"
          contents:
           - licenca.qmd





format:
  html:
    theme:
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    toc-title: "Nessa página"
