project:
  type: site
  output-dir: docs
lang: pt
site:
  title: "Relatórios reprodutíveis com R"
  footer: "Página criada usando [quarto](https://quarto.org/). <br>Licença de uso: [Creative Commons Atribuição-Compartilha Igual (CC BY-SA)](licenca.qmd)."
  repo-url: https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios
  twitter-card: true
  creator: "@beamilz"
  site: "@beamilz"
  site-url: "https://www.ime.usp.br/verao/assets/images/logo_verao.png"
  image: "img/preview.png"
  navbar:
    type: dark
    background: primary
    left:
    logo: https://www.ime.usp.br/verao/assets/images/logo_verao.png
    right:
      - icon: github
        href: https://github.com/beatrizmilz/2022-curso-de-verao-ime-usp-relatorios
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Informações sobre o curso"
        contents:
          - href: index.qmd
            text: Página inicial
          - informacoes-gerais.qmd
          - profs.qmd
          - bibliografia.qmd
          - faq.qmd
      - section: "Outras informações"
        contents:
          - licenca.qmd


format:
  html:
    theme:
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    toc-title: "Nessa página"



