---
title: "Relatórios reprodutíveis com R <br><br> Curso de Verão IME-USP 2022"
---

## Descrição

 No curso utilizaremos a linguagem de programação R e a interface de desenvolvimento RStudio. Primeiramente será apresentada uma introdução ao conceito de reprodutibilidade no contexto de desenvolvimento em R, e discutiremos boas práticas ao longo do curso. 
 
Utilizaremos o RMarkdown (<https://rmarkdown.rstudio.com/>), um pacote que possibilita criar relatórios reprodutíveis no R, como: listas de exercícios, relatórios, apresentações em HTML, apresentações em powerpoint, relatórios em word, relatórios interativos, entre outros. 

Aprenderemos também a criar relatórios reprodutíveis utilizando relatórios parametrizados, que permitem especificar parâmetros para customizar a análise, o que é muito útil para criar relatórios que podem ser reutilizados. 

Além disso, o conceito de controle de versão com Git será apresentado e também como podemos configurar o Git e o GitHub no RStudio para que seja possível versionar os projetos que criaremos em R. Também aprenderemos a disponibilizar o conteúdo criado no curso de forma online, através do GitHub.



## Público Alvo

- Estudantes de graduação que desejam se aprofundar no conhecimento do R.

- Profissionais do mercado de trabalho que usam o R e desejam aprimorar os seus conhecimentos.

- Pessoas na academia com interesse em tornar suas análises e códigos mais legíveis, reprodutíveis, eficientes e organizados.

## Pré-requisitos

É recomendado que as pessoas participantes estejam familiarizadas com o conteúdo do curso Introdução à programação em R.

## Método avaliativo

- Exercícios (em classe e extraclasse)

- Projeto prático final (extraclasse)


## Informações gerais

**Carga horária:** 15h (5 aulas de 3h)

**Local:** Online

**Datas:** 2, 7, 9, 14, 16 de fevereiro de 2022 (2ª e 4ª)

**Horário:** Manhã (09h-12h)

**Vagas:** 75

> Informações em breve no site do [Programa de Verão IME-USP](https://www.ime.usp.br/~verao/).
 
